# Generated by Django 4.0 on 2025-04-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_card_image_deck_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='is_active',
        ),
    ]
